name: Run Unit Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout test repository
      uses: actions/checkout@v2
      with:
        repository: IT-Hogskolan-Stockholm/JAVA-TEST-REPO # Uppdatera med ditt GitHub-användarnamn och namnet på testrepositoryt
        ref: main

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'

    - name: Compile and run unit tests
      run: |
        javac -cp .:./lib/junit-jupiter-api-5.10.2.jar:./JU24/JPROG/*.java
        java -cp .:./lib/junit-jupiter-api-5.10.2.jar:./JU24/JPROG org.junit.runner.JUnitCore Excercise-1-1-Test
